name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
        django-version: 
          - '>=2.1,<2.2'
          - '>=2.2,<2.3'
          - '>=3.0,<3.1'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install "django${{ matrix.django-version }}" -e .[tests]
      - name: Run tests
        run: |
          pip install codecov
          coverage run --rcfile=.coveragerc runtests.py
      - name: Upload coverage to Codecov
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: codecov
